# This file is automatically generated by kinfra from Bitwarden secrets
# Do not edit manually

# R2/S3 Backend Configuration
bucket     = ""
key        = "kubernetes/terraform.tfstate"
region     = "auto"
endpoints = {
  s3 = ""
}
access_key = ""
secret_key = ""
skip_credentials_validation = true
skip_metadata_api_check = true