# Serena Project Configuration for KInfra
# https://github.com/oraios/serena

# プロジェクト名
name: kinfra

# 除外パターン - ビルド成果物やキャッシュディレクトリを除外
exclude_patterns:
  # Gradle関連
  - "**/build/**"
  - "**/.gradle/**"
  - "**/gradle-wrapper.jar"

  # IDE関連
  - "**/.idea/**"
  - "**/.vscode/**"
  - "**/*.iml"

  # その他のビルド成果物
  - "**/bin/**"
  - "**/out/**"
  - "**/.kotlin/**"

  # ログとキャッシュ
  - "**/logs/**"
  - "**/.cache/**"

  # 依存関係
  - "**/node_modules/**"

# コメント: Kotlinプロジェクト向けの最適化設定
# Serenaはビルド前のソースコードを解析するため、
# ビルド成果物を除外することでパフォーマンスが向上します
