name: CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - .github/workflows/ci.yml
      - buildSrc/**
      - gradle/**
      - kodel/**
      - action/**
      - app-web/**
      - iac/**
      - kinfra-api/**
      - kinfra-cli/**
      - kinfra-infra/**
      - core/**
      - build.gradle.kts
      - gradle.properties
      - settings.gradle.kts
  pull_request:
    branches:
      - main
      - dev
    paths:
      - .github/workflows/ci.yml
      - buildSrc/**
      - gradle/**
      - kodel/**
      - action/**
      - app-web/**
      - iac/**
      - kinfra-api/**
      - kinfra-cli/**
      - kinfra-infra/**
      - core/**
      - build.gradle.kts
      - gradle.properties
      - settings.gradle.kts

jobs:
  ktcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p ./cache/app
          mkdir -p ./cache/.gradle
      - name: Cache something
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build with GitHub Actions cache
        run: |
          docker buildx build \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            -f Dockerfile_test .

      - run: docker compose -f compose.test.yml up test --exit-code-from test
      - run: docker compose -f compose.test.yml logs
        if: always()
