name: CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '**/*.gradle*'
      - '.github/workflows/ci.yml'
      - 'gradle.properties'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '**/*.gradle*'
      - '.github/workflows/ci.yml'
      - 'gradle.properties'

permissions:
  contents: read

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dorg.gradle.build-cache=true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run tests and lint
        run: |
          ./gradlew test ktlintCheck --continue || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            **/build/test-results/**/*.xml
            **/build/reports/tests/**
          retention-days: 30