name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    name: Build and Release JARs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_NUMBER=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Run tests
        run: ./gradlew test
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION_NUMBER }}

      - name: Build CLI Shadow JAR
        run: ./gradlew :app-cli:shadowJar
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION_NUMBER }}

      - name: Build Web Shadow JAR
        run: ./gradlew :app-web:shadowJar
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION_NUMBER }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            app-cli/build/libs/kinfra-cli-*.jar
            app-web/build/libs/kinfra-web-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}